### ISSUE TITLE
没断在函数头，但在断的时候执行快捷键，提示获取不到这个值

### ISSUE THREAD

**Issue by BroilFish** [LeadroyaL/IDA_ARM_Unwind#1]
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "E:/ida7.3/plugins/arm_unwind_plugin.py", line 553, in run
    unwind_with_gui()
  File "E:/ida7.3/plugins/arm_unwind_plugin.py", line 523, in unwind_with_gui
    return unwind_now(True)
  File "E:/ida7.3/plugins/arm_unwind_plugin.py", line 513, in unwind_now
    _pcs = get_unwinder().unwind_all()
  File "E:/ida7.3/plugins/arm_unwind_plugin.py", line 30, in unwind_all
    while self.unwind_single_frame(_status):
  File "E:/ida7.3/plugins/arm_unwind_plugin.py", line 76, in unwind_single_frame
    print 'pc', '%0.8x' % _status.getRx(_status.PC_INDEX)
TypeError: %x format: a number is required, not NoneType

**Comment by LeadroyaL** [comment]
```
                    # 5. lr -> pc
                    _status.setRx(_status.PC_INDEX, _lr2pc(lr_value))
                    print 'pc', '%0.8x' % _status.getRx(_status.PC_INDEX)
                    return True
```

75行setRx 了，76行 getRx，失败了说明 _lr2pc 返回了一个 None；
是通过 lr 推测 pc 时候失败的，要么是 lr 的值不正确，要么是 _lr2pc 写错了，还请多提供一些线索。
